#!/bin/bash

SETTINGS=/etc/nubis-config/active.sh

if [ -r $SETTINGS ]; then
  . $SETTINGS
else
  echo "Couldn't read settings from $SETTINGS"
  exit 1
fi

if [ ! -r /var/lib/mysql/nubis/MASTER ]; then
  echo "We are the MySQL primary master, so we care"
else
  echo "We are not the MySQL primary master, so we don't care"
  exit 0
fi

if [ "$MYSQL_ACTIVE" == "1" ]; then
  MYSQL_READ_ONLY="OFF"
else
  MYSQL_READ_ONLY="ON"
fi

echo "Setting MySQL readonly status to : $MYSQL_READ_ONLY"

mysql -e "set GLOBAL read_only=$MYSQL_READ_ONLY"
